config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to:'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to:'session#new'
  post 'login', to:'session#create'
  delete 'login', to:'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    belongs_to :user
    validates :title, presence: true, length: {minimum: 5 , maximum: 50}
    validates :description, presence: true, length: {minimum: 5 , maximum: 400}
end

app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase}

    has_many :articles, dependent: :destroy
    validates :username, presence: true,
        uniqueness: { case_sensitive: true },
        length: {minimum: 3, maximum:25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,
        uniqueness: { case_sensitive: true },
         length: { maximum:105},
         format: { with: VALID_EMAIL_REGEX}

    has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end


    def require_user
        if !logged_in?
            flash[:error] ="Your not Authorized to perform this action!"
            redirect_to login_path
        end

    end

   

    
end
# https://motorrad-x.herokuapp.com/

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  def show  
    # @article = Article.find(params[:id]) 
    # we decleared before_action to perform the set_article method before running each function that we decleared with that
  end

  def index

    @articles = Article.paginate(page: params[:page], per_page: 8)
  end

  def new

    @article = Article.new
    
  end

  def edit
    # @article = Article.find(params[:id])
  end


  def create
    
    # puts render plain: params[:article]
    @article = Article.new(article_params)
    @article.user = current_user
    @article.save
    Rails.logger.info @article.errors.full_messages
    if @article.errors.empty?
      flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update

    # @article = Article.find(params[:id])
    
    if @article.update(article_params)
      flash[:notice] = 'Article is successfully upadated'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    # @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  rescue => e 
    flash[:error] = 'Article doesnt exist!'
    redirect_to articles_path
  end

  # we are using this inside the two function above such as update and create. there we jus passing the function name insted of repeating the same code
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user

    if current_user != @article.user && !current_user.admin?
        flash[:error] ="You only allowded to update your articles!"
        redirect_to @article
    end
end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

        redirect_to articles_path if logged_in?
    end

    def about
    
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new


    end


    def create

        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            flash[:notice] = "Logged in successfully"
            session[:user_id] = user.id
            redirect_to user
        else
            flash.now[:error] = "Thre was a problem with your given input"
            render 'new'
        end
    end


    def destroy
        session[:user_id] = nil
        flash[:notice] = "successfully logged out!"
        redirect_to login_path

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.paginate(page: params[:page], per_page: 8)
    end
    def new
        @user = User.new
    end


    def show
        @user = User.find(params[:id])
        @articles = @user.articles

    rescue => e
        flash[:error] = "User unavailable!"
        redirect_to users_path
    end


    def edit
        @user = User.find(params[:id])
    end


    def update
        @user = User.find(params[:id])
        
        @user.update(params.require(:user).permit(:username, :email, :password))
        
        if @user.errors.empty?  
            flash[:notice] = "Your account has been updated successfully"
            redirect_to @user
        else
            render 'edit'
        end


    end



    def create
        @user = User.new(user_params)
        if(@user.save)
            flash[:notice] ="User created successfully"
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def destroy
        
        @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:error] ="Profile and all associated articles have been deleted successfully!"
        redirect_to articles_path

    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        @user = User.find(params[:id])
        if (current_user != @user && !current_user.admin?)
            flash[:error] ="You only allowded to update your profile!"
            redirect_to users_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user)
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end


    

    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<div class="container ">
    <div class="row">
        <% @articles.each do |article| %>
            <div class="col-3 mt-4" >
                <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem;">
                    <%= image_tag "book.jpeg", class: "car-img-top", alt: "Book" %>
                    <div class="card-body">
                        <h5 class="card-title"> <%=article.title %> </h5>
                        <%# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> %>
                        <%= link_to 'Read more', article_path(article.id), class:"btn btn-primary d-md-block" %>
                    </div>
                    <div class="crad-footer text-muted">
                        <small> Added at <%= time_ago_in_words(article.created_at)%></small>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>
<div class="row justify-content-center">
<%= form_with(model: @article,class:"card shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
<div class="form-group">
<%= f.label :title%> <br>
<%= f.text_field :title, class: "form-control" %>
</div>

<p>
<%= f.label :description %> <br>
<%= f.text_area :description,rows:7 ,class: "form-control"%>
</p>

<p>
<%= f.submit class:"btn btn-primary" %>
</p>
</div>

<% end %>

app/views/articles/create.html.erb
<h1>showing the newly created article</h1> 

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Go Back', articles_path, class:"btn btn-primary"%></>

app/views/articles/index.html.erb
<h1 style="font-family:Trebuchet MS" class="text-center">Article list </h1>

<%= render 'articles'%>
<br>
    <div class="apple_pagination .current">
        <%= will_paginate @articles, :container => false %>
    </div>

app/views/articles/new.html.erb
<h1>Create  a new article</h1>

<%= render 'form' %>

<%= link_to 'Go Back', articles_path, class: "btn btn-primary"%></>

app/views/articles/show.html.erb
<div>
    <div class="mx-auto" style="width: 300px;">
        <h3 style="font-family:Trebuchet MS">showing articles detail</h3>  
        <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 25rem;">
            <%= image_tag ("book.jpeg") %>
            <div class="card-body">
                <div class="container">
                <small>
                Article by <%= @article.user.username%>
                </small>
                <h5 class="card-title"><%= @article.title %> </h5>
                <p><%= @article.description %></p>
                <div>
            </div>
            <div class="crad-footer text-muted">
                <small> Added at <%= time_ago_in_words(@article.created_at)%></small>
            </div>
        </div>
    </div>

<% if( logged_in? && (current_user.username ==@article.user.username || current_user.admin?)) %>

    <div class=" row text-center mt-2">
        <%=link_to'update', edit_article_path(@article), class:'btn btn-warning mt-2' %>
        
        <%=button_to'Delete', article_path(@article), method: :delete, class:'btn btn-warning mt-2'%>
    </div>
<%end%>
    <%=link_to 'Go Back', articles_path,class:'btn btn-warning mt-2' %>
</div>

app/views/layouts/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->


<footer class="page-footer font-small special-color-dark pt-4 foot">
<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2021 Copyright:
    <a class="text-white" href="https://MotorradX.com/">MotorradX.com</a>
</div>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motorradx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  <br>
    <ul class="nav nav-pills nav-fill">
      <li class="nav-item">
        <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        <%= link_to 'Home ', root_path, class:"nav-link " %>
      </li>
      <li class="nav-item">
        <%= link_to 'MotorradX Bloggers', users_path, class:"nav-link nav-fill" %>
      </li>
      
      
      <% if(logged_in?)%>

        <li class="nav-item">
        <%= "ADMIN"  if current_user.admin?%>
        <%= link_to current_user.username, user_path(current_user), class:"nav-link " %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log out ', login_path,method: :delete, class:"nav-link " %>
        </li>
      <%else%>
        <li class="nav-item">
        <%= link_to 'Log in ', login_path, class:"nav-link " %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up ', signup_path, class:"nav-link " %>
      </li>
      <%end%>

      <li class="nav-item">
        <%= link_to 'About ', about_path, class:"nav-link " %>
      </li>
    </ul>

</head>

  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    <div class="container">
        <div class="jumbotron">
            <br>
            <h1 class="display-4" class="text-secondary">MotorradX</h1>
            <p class="lead" style="font-family:Trebuchet MS">Read out the latest articles on MotorradX </p>
            <hr class="my-4">
            <p></p>
            <p class="lead">
            </p>
        </div>
    </div>
    <div class= "container">
      <% flash.each do |name,msg|%>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="error"><strong><%=msg%></strong> </div>
              
              <button type="button" class="fade" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
          
      <%end%>
      <div>
          <%= yield %>
      </div>
      
    </div>
    <%= render 'layouts/footer'%>  
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
<p style="font-family:Trebuchet MS">
MotorradX India is a licensed publication of 'MotorradX', a British automobile publication by Haymarket Motoring Publications Ltd. It is part of Haymarket SAC Publishing (India) Pvt. Ltd., a joint venture between Haymarket and Sorabjee Automotive Communications.
MotorradX India is published as a monthly magazine and currently enjoys the highest readership among automobile magazines in India (IRS-2009 R1 report). A television show titled 'The MotorradX Show' also airs weekly on Times Now and ET Now which enjoys the highest viewership among Indian automobile programmes (source). Autocar India has a strong digital presence with the website providing a daily feed of automobile news, updates and reviews. The Autocar India YouTube channel features numerous videos with reviews, comparisons and other exciting automotive content. MotorradX India's digital presence extends to Twitter, Facebook, Instagram and Google+.
</p>
</div>
<div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                    <h5 class="card-title">MotorradX Articles</h5>
                    <p class="card-text">Read out the latest articles in MotorradX</p>
                    
                    <%= link_to 'Articles', articles_path, class: "btn btn-primary" %>
                    </div>
                </div>
            </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">Home</h5>
                        <p class="card-text">MotorradX</p>
                        <%# <a href="#" class="btn btn-primary" <%= link_to 'About ', about_path %> 
                        <%= link_to 'Home ', root_path, class: 'btn btn-primary' %>
                    </div>
                </div>
            </div>
        </div>
</div>

app/views/pages/home.html.erb
<div class="container">
        <div class="row">

            <div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">Sign Up to MotorradX</h5>
                        <p class="card-text">Sign Up and Explore Articles</p>
                        <%# <a href="#" class="btn btn-primary" <%= link_to 'About ', about_path %> 
                        <%= link_to 'Sign Up ', signup_path, class: 'btn btn-primary' %>
                    </div>
                </div>
            </div>

            <div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">Log in to MotorradX</h5>
                        <p class="card-text">Log in and Explore Articles</p>
                        <%# <a href="#" class="btn btn-primary" <%= link_to 'About ', about_path %> 
                        <%= link_to 'Log in ', login_path, class: 'btn btn-primary' %>
                    </div>
                </div>
            </div>
            <div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">MotorradX Articles</h5>
                        <p class="card-text">Read out the latest articles in MotorradX</p>
                        
                        <%= link_to 'Articles', articles_path, class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-body">
                            <h5 class="card-title">About MotorradX</h5>
                            <p class="card-text">Learn more about us!</p>
                            <%# <a href="#" class="btn btn-primary" <%= link_to 'About ', about_path %> 
                            <%= link_to 'About ', about_path, class: 'btn btn-primary' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
    

app/views/session/new.html.erb
<h1 class="text-center mt-4">Log in</h1> 

<div class="container">
    <div class="row justify-content-center">
    <%= form_with(scope: :session, url: login_path, class:"card shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group">
            <label class="form-control-label">EMAIL</label>
            <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <label class="form-control-label">PASSWORD</label>
            <%= f.text_field :password, class: "form-control",type:"password"%>
        </div>

        <div class="col-lg-12 loginbttm">
            <div class="col-lg-6 login-btm login-text">
            </div>
            <div class="col-lg login-btm login-button">
                <%= f.submit "Log in", class:"btn btn-outline-primary" %>
            </div>
        </div>
    <% end %>
    <div class="col-lg-1 login-btm login-button">
    <%=link_to "Back", users_path, class:"btn btn-outline-primary" %>
    </div>

</di>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissable fade show role=alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h1>The following errors prevented the <%= obj.class.name.downcase%> from beging saved</h1>
        <% obj.errors.full_messages.each do |msg| %>
                <ul>
                    <li><%=msg%></li>
                </ul>
            <% end %>
            
        </div>
    
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
    <%= render 'shared/errors', obj: @user%>
    <%= form_with(model: @user,class:"card shadow p-3 mb-5 bg-info rounded", local: true ) do |f| %>
        <div class="form-group">
            <label class="form-control-label">USERNAME</label>
            <%= f.text_field :username, class: "form-control" %>
        </div>
        <div class="form-group">
            <label class="form-control-label">EMAIL</label>
            <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <label class="form-control-label">PASSWORD</label>
            <%= f.text_field :password, class: "form-control",type:"password"%>
        </div>

        <div class="col-lg-12 loginbttm">
            <div class="col-lg-6 login-btm login-text">
            </div>
            <div class="col-lg-6 login-btm login-button">
                <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class:"btn btn-outline-primary") %>
            </div>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">MotorradX's Bloggers</h1>
 <div class="container center  ">
    <div class="row">
        <% @users.each do |user| %>
            <div class="col-3 mt-4" >
                <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 18rem;">
                    <%= link_to gravatar_for(user), users_path(user)%>  
                    <div class="card-body">
                        <h5 class="card-title text-center mt-4"> <%=user.username %> </h5>
                        <p class="card-text"><%=pluralize(user.articles.count,"article") %></p>
                        <%# <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> %>
                        <%= link_to "View Profile", user,class:"btn btn-primary d-md-block" %>
                         <br>
                        <% if logged_in? %> 
                            <% if current_user.username ==user.username %>
                                <%= link_to 'Edit Profile', edit_user_path(user), class:"btn btn-primary d-md-block" %>
                            <%end%>
                            <%if current_user.admin?%>
                            <br>
                                <%= link_to "Delete profile", user_path(user),method: :delete, data: {confirm:"Are you sure that you want to delete?"} ,class: "btn btn-danger" %>
                            <%end%>
                        <%end%>
                    </div>
                    <div class="crad-footer text-muted">
                    </div>
                </div>
            </div>
        <%end%>
    </div>
</div>
    <div class="apple_pagination .current">
        <%= will_paginate @users, :container => false %>
    </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> create new profile</h1> 
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username%>'s profile</h1> 

<%= gravatar_for @user%>
<div class="text-center mt-4">
    <% if( logged_in? && current_user.username ==@user.username) %>
        
        <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary "%>
        <%= link_to "Log out", login_path, method: :delete, class: "btn btn-primary "%>
        <%= link_to "New Article", new_article_path, class: "btn btn-primary "%>
        <%= link_to "Delete profile", user_path(current_user),method: :delete, data: {confirm:"Are you sure?"} ,class: "btn btn-danger" %>
    <%end%>
    <%= link_to "Back", users_path, class: "btn btn-primary "%>
</div>

<h3 class="text-center mt-4">Articles</h3> 

<%= render 'articles/articles'%>